### ISSUE TITLE
CI&デプロイをAWS(EC2, CodeDeploy)でやってみる

### ISSUE THREAD

**Issue by win2cot** [DGZ48/redman#17]
1. 開発者がGitHubにコードをPUSHする
2. CircleCIがテストを実行する
3. CircleCIがモジュールをS3にアップロードする（masterブランチのみ）
4. CodeDeployがEC2にデプロイする
   - S3へのPUTをトリガーにCodeDeployが起動？
   - CircleCIがCodeDeployをキック？
   - CodePipeline？

**Comment by win2cot** [comment]
https://github.com/DGZ48/redman/pull/16

**Comment by win2cot** [comment]
GitHubへPUSH、CircleCI、S3にファイルアップ、CodePipelineが起動、CodeDeployがキックされて入れ替え
が行われる

**Comment by inabajunmr** [comment]
とりあえずレベルでREADME.mdに
https://github.com/DGZ48/redman/blob/master/README.md#how-deploy-to-development-environment-automaticaly

**Comment by win2cot** [comment]
https://github.com/DGZ48/redman/pull/16 で対応済み
