### ISSUE TITLE
Masterで静的リソースが見えなくなった

### ISSUE THREAD

**Issue by inabajunmr** [DGZ48/redman#18]
https://github.com/DGZ48/redman/commit/d40e3061f1d28a3fd20e3523e3c28ea3d2b5ffbf
これの直前は見える

**Comment by inabajunmr** [comment]
直した
https://github.com/DGZ48/redman/commit/3166d77b6c76f5155bbf8b1092b66cc4a62084a7

**Comment by win2cot** [comment]
これよくきづけたね。
