### ISSUE TITLE
超大雑把な構成を考える

### ISSUE THREAD

**Issue by inabajunmr** [DGZ48/redman#2]
# なんとなくイメージ
* remoサービス
　→remoからシグナルとそのシグナルなんなの？を抽出
 * シグナルサービス
  →赤外線シグナルのリソース管理
 * ワークフローサービス
  →シグナルの組み合わせを定義
 * IFTTTサービス
  →シグナルの組み合わせをIFTTTにデプロイ
　　→これ最終的にはAPI叩かないといけないからシグナルの組み合わせをAPIの呼び出し順に戻せないとダメ？
　　　→シグナルサービスのリソースとしてこのAPIをこのパラメータで呼ぶとシグナル呼べます的な？
 * Webアプリ
　→ここで何できるかを先に詰めるべきかも⭐️

**Comment by inabajunmr** [comment]
先こっちかな
https://github.com/DGZ48/redman/issues/3

**Comment by inabajunmr** [comment]
とりあえずこのイメージ
https://cacoo.com/diagrams/9lm4vRTa7oxogelN#E7D7C

APIのエンドポイントとパラメータのセットをリソースとしてもっててその組み合わせをどうするか？のワークフローを定義出来る感じ

**Comment by win2cot** [comment]
せやせや

**Comment by inabajunmr** [comment]
ふつうのwebアプリでモノリシック
