### ISSUE TITLE
ユーザ情報を自前でDBに登録しない

### ISSUE THREAD

**Issue by inabajunmr** [DGZ48/redman#44]
仕組みがある模様
https://qiita.com/kunikunipon/items/3a9bd6aaa2756456fe38

**Comment by win2cot** [comment]
今のsecurityのやつと完全に別な気がするね、これ。

**Comment by inabajunmr** [comment]
べつですね
なんか今のとどっちがいいかでいうと別に今のでも良い気がしたのでいったんcloseで
