### ISSUE TITLE
デプロイの準備

### ISSUE THREAD

**Issue by inabajunmr** [DGZ48/redman#7]
AWS

構成とか？

**Comment by inabajunmr** [comment]
slackからコピペ by @kashiwaguma-hiro 
１．AWS（1年無料枠を誰かのアカウントで…？）
２．GCP（同上）
３．Dockerでとりあえず環境作っとく
４．PaaSの無料枠(IBM Cloud)で動かす (edited)

**Comment by win2cot** [comment]
> １．AWS（1年無料枠を誰かのアカウントで…？）
のイメージではあったよ。
今まで通り無料枠じゃなくて支払い発生でも別にいいかなと思ってました。

しばらく開発環境だと思うんだけど、PUSHしてCircleCIでテスト回して、通ったら環境に自動反映できればなんでもいいです。（AWSにこだわりはないです）

本番環境は、そもそも作るかって話もあるけど、まぁ後で決められればいいかしら。

**Comment by win2cot** [comment]
GitHub -> CircleCI -> S3 -> CodeDeploy -> EC2
で作っていい？

**Comment by inabajunmr** [comment]
CodeDeployのキックは手動のイメージですか？

**Comment by inabajunmr** [comment]
CircleCIがS3にアップした後CodeDeployを叩く？

**Comment by win2cot** [comment]
いや、自動で。
できれば、masterブランチの更新＆CircleCIのテストが全て通った場合　にしぼりたい。

**Comment by inabajunmr** [comment]
CodeDeployをキックするのはCircleCIですか？
（S3をCodeDeployがオブザーブして勝手にデプロイとかできるんだっけ的なことを考えています）

**Comment by win2cot** [comment]
コメントが早すぎるｗ

CircleCIはS3へのPUTまで。
CodeDeployがS3をobserveしてて勝手にデプロイ。

の想定です。（今調べてる）

**Comment by inabajunmr** [comment]
S3へのアップロードをトリガーにLambdaをキックしてLambdaがCodeDeployを叩く例があるところを見てるとないような気がしています（新しくできたとかはあるかも）
http://aws.typepad.com/sajp/2015/04/automatically-deploy-from-amazon-s3-using-aws-codedeploy.html

CodePipelineをかませばいけるっぽいです

**Comment by win2cot** [comment]
> CodeDeployがS3をobserveしてて勝手にデプロイ。

これが無理なんじゃないかってこと？

**Comment by inabajunmr** [comment]
ですー

**Comment by inabajunmr** [comment]
ドキュメントがっつり見たわけじゃなくてできるとしたら↑の構成変だなと思っただけですが

**Comment by win2cot** [comment]
- GitHub -> CircleCI -> S3 -> ElasticBeansTalk -> EC2
- GitHub -> CircleCI -> EC2

とかはありえるのかな。

**Comment by inabajunmr** [comment]
circleCIがcodedeployをキックじゃダメですか？

**Comment by inabajunmr** [comment]
なんかcircleciにデフォルトでAWSのCDツールと統合してた気がするな

**Comment by win2cot** [comment]
- GitHub -> CircleCI -> CodeDeploy -> EC2

あ、全然これでもいい。

**Comment by inabajunmr** [comment]
こんな感じですかね
https://qiita.com/hardreggaecafe/items/7ff3ada575a1100fa4a2

**Comment by inabajunmr** [comment]
これはこんな感じですかね（カオス）
```
GitHub 1-> CircleCI 2-> S3 <-------
                                3-> CodeDeploy ↖︎4
                                                    ↘︎5------->EC2
```

**Comment by win2cot** [comment]
わけわからんｗ

**Comment by win2cot** [comment]
#17 はやった。

**Comment by inabajunmr** [comment]
とりあえずこのラインは満たしてるかなあという気がするのでcloseで
なんかやりたいことあったら別Issue
